name = "DaggerSeamCarving"
uuid = "bc9abd6a-8236-43e7-a63a-23b604239553"
version = "0.0.1"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Dagger = "d58978e5-989f-55fb-8d15-ea34adc7bf54"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
